### ISSUE TITLE
Item Duplication Bug

### ISSUE THREAD

**Issue by krypticbit** [Terumoc/terumet#16]
If a terumetal alloy smelter is moved via a mesecon piston, it drops the stuff inside it without clearing it from the inventory.  Players have been using this to duplicate items.  Please fix this, as it is a very big disadvantage to using terumet.

**Comment by CubicMelon** [comment]
My apologies for not keeping up to date on here! I haven't had much time to work on anything Minetest related.

It can't be too hard to fix, even if it just means making the machines unable to be piston-moved.

I'll look into fixing it as soon as I can.

**Comment by CubicMelon** [comment]
Okay, I sat down and took a look and I have some good and bad news.

The good news: Making machines unmovable by pistons is simple, but because I'm assuming you're using an old version it's not easy to go back and add the fix retroactively.

note to future me or anyone brave enough to try adding this fix:
if the mesecon mod is active, every machine node needs to be called in `mesecon.register_mvps_stopper(<machine node name>, true)`

Furthermore, the bad news: it looks like development of Minetest 5.0 has changed something and broken the ordering of some of the callbacks that the mod depended on. So, further development without some major debugging and changing how things works (which I don't really have the time for at the moment) is probably not possible....unless the engine somehow changes back. I'll check on it once in a while when I get the chance though.

**Comment by CubicMelon** [comment]
Fix coming soon™️

**Comment by CubicMelon** [comment]
Fixed. Machines cannot be moved via mesecon piston anymore.
