### ISSUE TITLE
enhancement: no easy infinite obsidian

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#22]
Using tubelib (and probably pipeworks, and similar mods) it's easy to set up a machine that just creates infinite obsidian: obsidian goes in the crystal vulcanizer, 2-3 obsidan crystals come out, which can each be smelted into obsidian again automatically, and automatically fed back into the vulcanizer. While having a way to generate infinite obsidian is really useful given that lava is quite rare on most servers, there's now other ways, i.e. using the lava melter w/ various setups.

I propose that  vulcanizer only ever create one crystal from a piece of obsidian, regardless of whether a crystalization upgrade is installed. 

If you like the idea, I can probably cook up a PR w/ this feature.

**Comment by CubicMelon** [comment]
That's certainly a fair option; I don't necessarily want to force this on servers or players who might not want "easy obsidian". As you suggested, it was originally in it because of how obnoxiously rare lava is on most servers. An option to make it only one for one wouldn't be a bad idea.

If you want to implement it, you're more than welcome to. Otherwise I'll check out adding this option myself when I get a chance to

**Comment by fluxionary** [comment]
Cool. I'll get started on a PR, and leave a way to make the behaviour a configurable option.
