### ISSUE TITLE
Enhancement: additional bracers

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#31]
Some players on our server have opined that they think there should be some more bracers with different properties. The best of these suggestions, in my opinion:

1. Enhanced stamina (from the stamina mod) - so you don't have to eat nearly as often
2. Immunity or resistance to damage from fire/lava
3. "Long reach" - the ability to break/place blocks farther away than normal.
4. Strength - tools work faster than normal

I haven't looked into how to implement these (though I know the admin pick from maptools has something like long reach), so I leave it up to you to decide whether these are fair/possible/reasonable.

**Comment by CubicMelon** [comment]
I certainly wouldn't mind putting in more Bracer options!

These are some good ideas, I'll check out how I might be able to make such things possible when I get the chance very soon.

**Comment by CubicMelon** [comment]
I just committed a change to bracers that adds Fire protection since that was a feature already in 3d_armor; however (for whatever reason...) by default 3d_armor does not have fire protection in armor activated unless some mod named "ethereal" is active.

The bracer works fine, but you will need to **specifically turn on** the option "enable fire protection" in 3d_armor for it to have any effect. The tool tip will change to mention that it's useless if it is not turned on.

I really like the idea of the other effects (better stamina/reach/tool speed) but from research I've discovered the following:

- The stamina mod does not have any external mod access to change its calculations. In order to make a bracer that affects stamina use, that mod will need to be changed.
- The minetest engine only looks at the current tool being used for speed and range. It's not really possible to modify the values beyond what is set for the specific tool being used. You *can* override a specific tool instance with new values (ie make a Stone Pickaxe ItemStack that has a better range than normal) but there's really no way to affect tool capabilities/features for a player in general rather than specific instances of tools.

**Comment by CubicMelon** [comment]
While I can't make bracers that have these effects, I did just commit an update that introduces upgraded versions of the tools that extend reach, increase speed or increase durability.

**Comment by fluxionary** [comment]
As far as I can tell, the reason that "fire protection" isn't enabled by default is that when it is, 3d_armor completely overrides how fire damage is calculated and which nodes inflict fire damage, and that might affect yet another mod. I'm not certain whether or not changing its default is a sensible option; I've submitted a (trivial) PR along with this query.  https://github.com/stujones11/minetest-3d_armor/pull/166

Adding extended reach as a general ability seems like it will take updates to core; I'm not going to tackle that now (though I might submit it as a feature request soon). 

Adding an API to stamina seems plausible, and I'd love to do that, but it's not my highest priority and I estimate it'll be a month or two (or more) till I get to it. I don't know if that's reason enough to keep this bug open, I'll leave that to you.

Upgraded tools sound awesome though :)

**Comment by CubicMelon** [comment]
Since it does seem like the stamina mod is no longer worked on, I might try to modify it myself. But yeah, no promises ;)

I'm quite happy with the new upgraded tools and look forward to seeing them on the server!

**Comment by fluxionary** [comment]
Not sure if a "stamina" bracer is needed anymore, but I've written an API for stamina:
https://github.com/minetest-mods/stamina/pull/26
