### ISSUE TITLE
Clarification: ore saw + dense ores

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#41]
A player just observed that the ore saw can't harvest the dense ores. I'm not offering an opinion on whether they should be vulcanizable (they're already quite powerful), but I like it when all the ore is at least harvest-able w/ the saw, for decoration. Not sure if there's another reason why they aren't harvest-able.

**Comment by CubicMelon** [comment]
I'm fairly sure I put off adding them when I first put the dense ores in because I was still deciding on this point about vulcanizing them.

I ended up deciding that they should be a nice early-tech find (before you have fancy stuff like Terumetal Specialization and Crystallizer Upgrades) but not really usable in the vulcanizer or anything, they're lucrative enough on their own.

BUT, there's no reason you shouldn't be able to pick them up with the saw for decorative purposes if you  like, so I added them to the options.
