### ISSUE TITLE
nodes are not properly registered as mvps stoppers

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#55]
The current code attempts to register *individual nodes in the world* when they are placed, instead of a type of node by itemstring. Didn't notice this on Blocky cuz we're still running some custom code that adds all the terumet machines anyway. I'm too brain dead to fix this right now, or I would.

**Comment by Terumoc** [comment]
I know this was working properly before, has the way the pistons worked or how immovable nodes are registered been changed with an update to that mod?

**Comment by CubicMelon** [comment]
I know it's not super clear because I wrote a lot without really considering other people looking at it, so let me try to clarify what the current code is doing:

`terumet.machine.register_on_new_machine_node( func )` registers `func` to be called every time any terumetal machine's node is **defined/registered**. All registered functions are called with the arguments of (id, def) where id = name of machine's node and def = definition table of the node.

Therefore the code in interop/mesecons.lua is doing the following "whenever a new terumetal machine node is defined, call mesecon.register_mvps_stopper(id, true)" -- where id is the name of the machine node being defined

in hindsight it would be more accurate to call it "register_on_new_machine_registration" or something

**Comment by CubicMelon** [comment]
well I just tested it and it sure doesn't seem to be working anymore for some reason, I'm able to piston machines all over the place. When I get back this evening I'm going to figure out why

**Comment by CubicMelon** [comment]
nevermind, figured out why -- interop/mesecons.lua wasn't being called

It seems there was a regression when I moved from checking for other mods via looking for global variables to using minetest.get_modpath (which is the recommended way) -- **mesecon** global variable vs. **mesecon_s_** modpack name was causing it to never be found

**Comment by CubicMelon** [comment]
also just to point it out, I did rename the "on new machine registration" function to `on_machine_registration` which is much clearer

**Comment by fluxionary** [comment]
Awesome, thanks.
