### ISSUE TITLE
Vacuum-packed food bonus sometimes doesn't apply when also using the stamina mod

### ISSUE THREAD

**Issue by fluxionary** [Terumoc/terumet#57]
Because stamina completely redefines `minetest.do_item_eat`, depending on the load order of that mod and this one, the vacuum-packed food multiplier may be ignored. 

I'm at a loss as to a *good* solution to this. Ideally, food values would be a property of the item, and vacuum-packed food would just increase that value. In reality, they're inaccessible, hidden inside a closure. 

An ad-hoc solution is to make "stamina" an optional dependency of terumet, though that feels wrong because there's nothing in terumet that explicitly or implicitly references stamina. 

Thoughts?

**Comment by CubicMelon** [comment]
Nice catch. Load order bugs are always a pain to figure out because of how transient they can be.

I think it's fine to add it as an optional dependency to fix the problem. I always considered the dependency system as a way to hint Minetest as to the "correct" order to load things, regardless of whether or not your mod actually references those mods directly or not. If in order to get the correct, expected behavior between the two mods Terumet must load after Stamina, so be it.

**Comment by fluxionary** [comment]
Awesome. I've thought about the issue some more myself, and that's still the best solution I have. I'll put in a PR in a few moments.

**Comment by CubicMelon** [comment]
Now that you mention it I remember not particularly liking the solution I ended up having to use in order to implement the increase in food effect, but as you say I don't think there's any other better way.

Thanks for taking care of it.

**Comment by fluxionary** [comment]
I'll chalk up the "ickiness" of the working solution, to the fact that the minetest devs seemed to think that monkey-patching was a good model for an extension API. i officially feel like i'm writing extensions for mac system 7.
