### ISSUE TITLE
Suggestion: Interoperability with stairsplus (moreblocks)

### ISSUE THREAD

**Issue by akozlovskiy119** [Terumoc/terumet#59]
Stairsplus mod automatically generates many variations of stairs/panels that are very useful for building. It would be great if all terumet blocks (except for maybe ore blocks?) could be sawed using this mod.

Default 'stairs' mod can be used as fallback when stairsplus is not installed (code example: https://notabug.org/TenPlus1/bakedclay/src/master/init.lua#L51)

**Comment by fluxionary** [comment]
@Terumoc This is something i could easily add under "interop" if you consent, but i'd recommend we put in a setting to enable moreblocks integration, instead of having it enabled by default. moreblocks adds a *ton* of items against the 32767 limit; a lot of mod-heavy servers already struggle w/ that.

**Comment by CubicMelon** [comment]
I did not know there was a hard limit of that number, that seems awfully low with running a lot of mods for sure. (Doesn't help that I've been away from minetest way too long to remember stuff like this...)

I'm always for more interop between mods supporting each others features, but yes it does sound like a good idea to make it optional.
