### ISSUE TITLE
Some items missing

### ISSUE THREAD

**Issue by MidnightPhantom** [Terumoc/terumet#71]
Some items of your mod like armor sets and doors won't appear in my inventory.
Even though my 3Darmor was up to date

**Comment by mrbid** [comment]
what inventory are you using? i3, unified?

**Comment by MidnightPhantom** [comment]
i3

**Comment by MidnightPhantom** [comment]
and default one

**Comment by mrbid** [comment]
It's due to the custom API for unified inventory being used to register those items, no one has added support for the i3 inventory, it's fairly easy to do but I don't think anyone will be adding support for this mod any time soon.

I suggest you use Unified Inventory. i3 is still very much in it's early stages of development, many bugs and infantile features, for example only recently did they update the skindsbd skin selection and still it's less user friendly than the default skinsdb UI for sfinv and unified inventory.

**Comment by mrbid** [comment]
It's due to the custom API for unified inventory being used to register those crafts (and unless your account has creative i3 wont show items with no registered crafts), no one has added support for the i3 inventory to terumet, it's fairly easy to do but I don't think anyone will be adding support for i3 in this mod (terumet) any time soon.

I suggest you use Unified Inventory because i3 is still very much in it's early stages of development, there are many bugs in i3 and many of the features are still infantile, for example only recently did they update the skinsbd skin selection and even after this "update" it's still less user friendly than the default skinsdb UI for sfinv and unified inventory.

Also Unified Inventory boots much faster than i3 does if your server crashes, and this is a big selling point from a player perspective, i3 on average takes 5-6 minutes on my server with 50k+ nodes, while Unified Inventory takes 3 minutes or less. That's thanks to a pr I submitted on behalf of a user called Test_User.

I put some significant effort into trying to make i3 usable, but I can assure you this inventory is a lost cause and that you should focus on Unified Inventory, in comparison to i3, no mods support i3 they all support Unified Inventory so you will always hit road bumps like this if you insist on using i3 - also - the i3 maintainer has no interest in helping other mods support their inventory beyond providing a very minimalist external API as their development ethos is very rigid.

i3 is better suited for servers that do not intend to use advanced or technical mods such as terumet.

https://github.com/minetest-mods/unified_inventory/

**Comment by MidnightPhantom** [comment]
And what about the default inventory they don't show in that one too

**Comment by MidnightPhantom** [comment]
Ok

**Comment by MidnightPhantom** [comment]
I wanted to ask you a question. 
Can I make a new dimension in Minetest like in Minecraft by despawning all the blocks present in the overworld. So that I can even access the nether when I am on singlenode mapgen

**Comment by MidnightPhantom** [comment]
Yeah I will reduce map generation limit too
